//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarOrder()
        {
            this.BarTable = new HashSet<BarTable>();
            this.OrderPositions = new HashSet<OrderPosition>();
        }
    
        public int BarOrderID { get; set; }
        public byte PaymentStatus { get; set; }
        public int BarOrderBarTableID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int PositionID { get; set; }
        public int WaiterID { get; set; }
        public int OrderPositionID { get; set; }
    
        public virtual Waiter Waiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarTable> BarTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPosition> OrderPositions { get; set; }
    }
}
