//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarOrder()
        {
            this.BarTable = new HashSet<BarTable>();
        }
    
        public int BarOrderID { get; set; }
        public byte PaymentStatus { get; set; }
        public int BarOrderBarTableID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int PoitionID { get; set; }
        public int WaiterID { get; set; }
    
        public virtual Waiter Waiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarTable> BarTable { get; set; }
    }
}
