
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Theke.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BarTable
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BarTable()
    {

        this.Reservation = new HashSet<Reservation>();

        this.BarOrders = new HashSet<BarOrder>();

    }


    public int BarTableID { get; set; }

    public Nullable<int> PositionX { get; set; }

    public Nullable<int> PositionY { get; set; }

    public Nullable<int> Width { get; set; }

    public Nullable<int> Height { get; set; }

    public Nullable<int> SeatAmount { get; set; }

    public string TableName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservation> Reservation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BarOrder> BarOrders { get; set; }

}

}
