//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySlip
    {
        public int DeliverySlipID { get; set; }
        public int SupplierID { get; set; }
        public string DeliverySlipNumber { get; set; }
        public int BillID { get; set; }
        public int StorageID { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
