//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySlip
    {
        public int DeliverySlipID { get; set; }
        public int SupplierID { get; set; }
        public string DeliverySlipNumber { get; set; }
        public int BillID { get; set; }
        public int StorageID { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
