
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Theke.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InvoicePosition
{

    public int InvoiceID { get; set; }

    public int PositionID { get; set; }

    public string ProductName { get; set; }

    public double Price { get; set; }

    public int Amount { get; set; }



    public virtual Invoice Invoice { get; set; }

}

}
