//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PriceHistory = new HashSet<PriceHistory>();
            this.Storage = new HashSet<Storage>();
        }
    
        public int ProductID { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public int AgeRatingID { get; set; }
        public int ProductUnitID { get; set; }
        public int ProducerID { get; set; }
        public int AlcoholAmount { get; set; }
        public int NutriantContentID { get; set; }
        public Nullable<int> EanNumber { get; set; }
        public int Deposit { get; set; }
        public int ItemAmount { get; set; }
        public int CategorieID { get; set; }
        public double MinPrice { get; set; }
        public double MaxPricce { get; set; }
        public Nullable<int> AveragePurchasePrice { get; set; }
        public string CreatedByID { get; set; }
        public string ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModfiedDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AgeRating AgeRating { get; set; }
        public virtual Category Category { get; set; }
        public virtual NutriantContent NutriantContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storage { get; set; }
    }
}
