
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Theke.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reservation
{

    public int ReservationID { get; set; }

    public System.DateTime Date { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public int PersonAmount { get; set; }

    public int BarTableID { get; set; }



    public virtual BarTable BarTable { get; set; }

}

}
