//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public System.DateTime Date { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int PersonAmount { get; set; }
        public int BarTableID { get; set; }
    
        public virtual BarTable BarTable { get; set; }
    }
}
