//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.DeliverySlip = new HashSet<DeliverySlip>();
        }
    
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string StreetName { get; set; }
        public int StreetNumber { get; set; }
        public int ZipCodeID { get; set; }
        public string OwnCustomerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverySlip> DeliverySlip { get; set; }
        public virtual ZipCode ZipCode { get; set; }
    }
}
