
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Theke.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Waiter
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Waiter()
    {

        this.BarOrders = new HashSet<BarOrder>();

    }


    public int WaiterID { get; set; }

    public string VName { get; set; }

    public string LName { get; set; }

    public string Nicname { get; set; }

    public string UserID { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BarOrder> BarOrders { get; set; }

}

}
